version: '3'
services:
  solr:
    image: solr:8
    environment:
      SOLR_HEAP: 4g
    ports:
      - "8983:8983"
    volumes:
      - .:/blacklight_config
    command: solr-precreate blacklight /blacklight_config
